cors:
  originPatterns: http://localhost:3000,http://localhost:8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mecompraae?useTimezone=true&serverTimezone=UTC
    username: dev
    password: M3Compr@A3
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show-sql: false